# clients.conf
# Localhost client (for radtest/testing inside container)
client localhost {
	ipaddr = 127.0.0.1
	proto = *
	secret = "${ENV{RADIUS_SHARED_SECRET}}"
	require_message_authenticator = no
	nas_type = other
}

client localhost_ipv6 {
	ipv6addr = ::1
	secret = "${ENV{RADIUS_SHARED_SECRET}}"
}
